name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-4.8
            cxxstd: "03,11"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: g++-4.8
          - toolset: gcc-5
            cxxstd: "03,11,14,1z"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: g++-5
          - toolset: gcc-6
            cxxstd: "03,11,14,1z"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: g++-6
          - toolset: gcc-7
            cxxstd: "03,11,14,17"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: g++-7
          - toolset: gcc-8
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: g++-8
          - toolset: gcc-9
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
          - toolset: gcc-10
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: g++-10
          - toolset: gcc-11
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:24.04
            os: ubuntu-latest
            install: g++-11
          - toolset: clang
            compiler: clang++-3.9
            cxxstd: "03,11,14"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: clang-3.9
          - toolset: clang
            compiler: clang++-4.0
            cxxstd: "03,11,14"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: clang-4.0
          - toolset: clang
            compiler: clang++-5.0
            cxxstd: "03,11,14,1z"
            container: ubuntu:18.04
            os: ubuntu-latest
            install: clang-5.0
          - toolset: clang
            compiler: clang++-6.0
            cxxstd: "03,11,14,17"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-6.0
          - toolset: clang
            compiler: clang++-7
            cxxstd: "03,11,14,17"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-7
          - toolset: clang
            compiler: clang++-8
            cxxstd: "03,11,14,17"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-8
          - toolset: clang
            compiler: clang++-9
            cxxstd: "03,11,14,17"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-9
          - toolset: clang
            compiler: clang++-10
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-10
          - toolset: clang
            compiler: clang++-11
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-11
          - toolset: clang
            compiler: clang++-12
            cxxstd: "03,11,14,17,2a"
            container: ubuntu:20.04
            os: ubuntu-latest
            install: clang-12
          - toolset: clang
            cxxstd: "03,11,14,17,20,2b"
            os: macos-15

    runs-on: ${{matrix.os}}
    container:
      image: ${{matrix.container}}
      volumes:
        - /node20217:/node20217:rw,rshared
        - ${{ startsWith(matrix.container, 'ubuntu:1') && '/node20217:/__e/node20:ro,rshared' || ' ' }}

    steps:
      - name: Setup container environment
        if: matrix.container
        run: |
          apt-get update
          apt-get -y install sudo python3 git g++ curl xz-utils

      - name: Install nodejs20glibc2.17
        if: ${{ startsWith( matrix.container, 'ubuntu:1' ) }}
        run: |
          curl -LO https://archives.boost.io/misc/node/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node

      - name: Install packages
        if: matrix.install
        run: sudo apt-get -y install ${{matrix.install}}

      - uses: actions/checkout@v2

      - name: Setup Boost
        run: |
          cd ..
          git clone --depth 1 https://github.com/boostorg/boost
          cd boost
          cp -r $GITHUB_WORKSPACE/* libs/align
          git submodule init libs/assert
          git submodule init libs/config
          git submodule init libs/core
          git submodule init libs/static_assert
          git submodule init libs/throw_exception
          git submodule init libs/headers
          git submodule init tools/build
          git submodule init tools/boost_install
          git submodule update
          ./bootstrap.sh
          ./b2 -d0 headers

      - name: Create user-config.jam
        if: matrix.compiler
        run: |
          echo "using ${{matrix.toolset}} : : ${{matrix.compiler}} ;" > ~/user-config.jam

      - name: Run tests
        run: |
          cd ../boost
          ./b2 -j3 libs/align/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} variant=debug,release

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: msvc-14.2
            cxxstd: "14,17,latest"
            target: 32,64
            os: windows-2019
          - toolset: msvc-14.3
            cxxstd: "14,17,latest"
            addrmd: 32,64
            os: windows-2022
          - toolset: gcc
            cxxstd: "03,11,14,17,2a"
            target: 64
            os: windows-2019

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Boost
        shell: cmd
        run: |
          cd ..
          git clone --depth 1 https://github.com/boostorg/boost boost
          cd boost
          xcopy /s /e /q %GITHUB_WORKSPACE% libs\align\
          git submodule init libs/assert
          git submodule init libs/config
          git submodule init libs/core
          git submodule init libs/static_assert
          git submodule init libs/throw_exception
          git submodule init libs/headers
          git submodule init tools/build
          git submodule init tools/boost_install
          git submodule update
          cmd /c bootstrap
          b2 -d0 headers

      - name: Run tests
        shell: cmd
        run: |
          cd ../boost
          b2 -j3 libs/align/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} address-model=${{matrix.target}} variant=debug,release
